<?xml version="1.0"?>
<package format="3">
  <name>onnxruntime_ros</name>
  <version>1.22.0</version>
  <description>Wrapper around the ONNX Runtime library for ROS 2 workspaces</description>

  <maintainer email="MatthijsBurgh@outlook.com">Matthijs van der Burgh</maintainer>

  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
